- services/proxy/pkg/config/defaults/defaultconfig.go
fixes https://github.com/opencloud-eu/opencloud/issues/193
> 'default' routing policy

- deployments/examples/opencloud_full/minio.yml
stops minio from printing a warning on startup
> use new env vars for minio account

- .woodpecker/docs.yaml
- docs/intro.md
- test case 1:
- test case 2:
- ...
> docs: devdocs skeleton

- pkg/version/version.go
> set correct opencloud version

- tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
Some feature items where off by one line.
> Fix expected failures file

- deployments/examples/opencloud_full/.env
When using `COMPOSE_FILE`, the `COMPOSE_PATH_SEPARATOR` defaults to
- `:` on Linux, Mac
- `;` on Windows
As the `COMPOSE_FILE` variable is constructed with `:`, the path separator needs to be explicitly changed on windows.
This shouldn't conflict with Linux or Mac as we're just explicitly setting the default value.
[Docker Documentation](https://docs.docker.com/compose/how-tos/environment-variables/envvars/#compose_path_separator)
Fixes the Docker Compose opencloud_full deployment example not running on Windows.
Error message: 
```
CreateFile C:\Users\felix\Desktop\opencloud\deployments\examples\opencloud_full\docker-compose.yml:opencloud.yml:collabora.yml: The filename, directory name, or volume label syntax is incorrect.
```
Kudos to user @butonic:matrix.org for identifying the issue …
> Fix: Docker Compose "opencloud_full" Windows Bug

- deployments/examples/opencloud_full/.env
- deployments/examples/opencloud_full/config/opencloud/apps.yaml
- deployments/examples/opencloud_full/config/opencloud/csp.yaml
- deployments/examples/opencloud_full/web_extensions/drawio.yml
- deployments/examples/opencloud_full/web_extensions/externalsites.yml
- deployments/examples/opencloud_full/web_extensions/importer.yml
- deployments/examples/opencloud_full/web_extensions/jsonviewer.yml
- deployments/examples/opencloud_full/web_extensions/progressbars.yml
- deployments/examples/opencloud_full/web_extensions/unzip.yml
Extensions from the `web-extensions` repo have been released. Adapting the full example accordingly.
> feat: use extensions in full example

- services/graph/pkg/service/v0/personaldata.go
We cannot assume the personal space of a user always matches his user id ... that would be nice, but is not a given. POSIX for example has to assign a random uuid, which is why the GPDR tests failed.
fixes https://github.com/opencloud-eu/opencloud/issues/282
@ScharfViktor  With this PR I still have four failing tests:
```
apiGraph/userGDPRExport.feature:75
apiGraph/userGDPRExport.feature:308
apiGraph/userGDPRExport.feature:413
apiGraph/userGDPRExport.feature:587
```
AFAICT because locally my admin user has an id `some-admin-user-id-0000-000000000000`
```
JSON Schema validation failed:
1. properties.event.properties.Executant.properties.opaque_id:
- "some-admin-user-id-0000-000000000000" does not match to ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}$ …
```
> look up personal space for GDPR export

- .gitignore
- deployments/examples/bare-metal-simple/README.md
- deployments/examples/bare-metal-simple/install.sh
This adds my simple install script to the main code repo. It is referenced there from the opencloud-eu website.
> [docs-only] Add the bare metal simple install script as example

- tests/acceptance/TestHelpers/UploadHelper.php
- tests/acceptance/bootstrap/FeatureContext.php
- tests/acceptance/bootstrap/OCSContext.php
- tests/acceptance/bootstrap/OcConfigContext.php
- tests/acceptance/bootstrap/SearchContext.php
- tests/acceptance/bootstrap/ShareesContext.php
- tests/acceptance/bootstrap/Sharing.php
- tests/acceptance/features/apiGraph/getApplications.feature
- tests/acceptance/features/apiNotification/emailNotification.feature
needed for CI
fix `gherkin lint` and `php-style`
> Fix gherkin lint

- services/idp/src/App.jsx
- test case 1:
- test case 2:
- ...
> fix(idp): add empty alt tag on decorative img

- deployments/examples/opencloud_full/config/opencloud/csp.yaml
- test case 1:
- test case 2:
- ...
> Fix csp.yaml for full deployment example

- deployments/examples/opencloud_full/config/opencloud/apps.yaml
- test case 1:
- test case 2:
- ...
> Remove wikipedia from app switcher in full deployment example

- .woodpecker.star
- test case 1:
- test case 2:
- ...
> fix: remove uneeded upload steps

- .woodpecker.star
This PR enables running localApiTests(apiSpacesDavOperation suite) in CI.
- Sub-issue: https://github.com/opencloud-eu/qa/issues/7
- test case 1:
- test case 2:
- ...
> Run localApiTests in CI

- .woodpecker.star
- tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
- tests/acceptance/expected-failures-without-remotephp.md
- tests/acceptance/features/apiActivities/activities.feature
- tests/acceptance/features/apiActivities/shareActivities.feature
- tests/config/woodpecker/fontsMap.json
This PR makes the following `localApiTests` pipeplines run in CI:
``` console
1. API-search1
2. API-search2
3. API-spaces
4. API-sharingNg
5. API-sharingNgShareInvitation
6. API-spacesShares
7. API-basic
```
- Sub-issue: https://github.com/opencloud-eu/qa/issues/7
- test case 1:
- test case 2:
- ...
> Run Api Tests in CI

- .woodpecker.star
- opencloud/Makefile
- opencloud/docker/Dockerfile.multiarch
Add docker multi arch build step for two platforms.
@dragonchaser I removed the go generate step, because running it inside the build container took more than 20 minutes.
The build time of the container build was above 17 minutes. That is not good. This step runs after all tests have been successful. It turns a nice 20min total run into 40 min easily. Can we speed things up?
- test case 1:
- test case 2:
- ...
> feat: add container builds

- services/idp/pkg/config/config.go
- services/idp/src/containers/Login/Login.jsx
fixes https://github.com/opencloud-eu/opencloud/issues/376
> add sign in page text

- .woodpecker.star
- test case 1:
- test case 2:
- ...
> fix: container builds

- .woodpecker.star
- pkg/version/version.go
Test with an alpha release if the workflows are working properly.
- test case 1:
- test case 2:
- ...
> chore: bump version

- .woodpecker.env
related https://github.com/opencloud-eu/web/pull/329
check flaky e2e in the CI
> update web commit

- .woodpecker.star
This PR enables `API-ocm` pipeline to run in CI.
- Fixes: https://github.com/opencloud-eu/qa/issues/10
- CI :robot:
> Run OCM tests pipeline in CI

- .woodpecker.star
While `posix` is not running by default I added the ability to run tests with it if you add a `[posix]` tag to the title
if no `[posix]` in the title -> `decomposed` fs
when we get green CI - I make posix by default
> run test with posix

- .woodpecker.star
Upload binaries to github release
- Fixes https://github.com/opencloud-eu/qa/issues/13
- automated
- created `v1.1.0-alpha.4`
> feat: add release build step

- pkg/version/version.go
Bump version to v1.1.0 for the upcoming rolling release.
> chore: bump version to v1.1.0

- .woodpecker.star
- tests/acceptance/features/cliCommands/backupConsistency.feature
This PR enables cliCommands tests pipeline run in CI.
- :robot:
> Run `cliCommands` tests pipeline in CI

- .woodpecker.star
- tests/config/woodpecker/serve-hosting-discovery.sh
Run all the WOPI tests in CI
- Fixes https://github.com/opencloud-eu/qa/issues/12
make sure WOPI protocol works great
:robot:
> Run wopi tests in CI

- .woodpecker.star
This PR cleans up all mentions of ocis and owncloud.
- Fixes: https://github.com/opencloud-eu/qa/issues/26
- :robot:
> Cleanup woodpecker

- .woodpecker.star
Convert regexes into glob patterns
- test case 1:
- test case 2:
- ...
> fix: fix path exclusion glob patterns

- .woodpecker.star
enable CS3 API tests in CI
- Fixes https://github.com/opencloud-eu/qa/issues/11
:robot:
> run CS3 API tests in CI

- tests/acceptance/docker/src/opencloud-base.yml
fix `opencloud` setup with docker `LOCAL_TEST=true STORAGE_DRIVER=posix make -C tests/acceptance/docker start-server`
> fix local setup

- services/graph/pkg/service/v0/driveitems.go
> Do not cache when there was an error gathering the data

- deployments/examples/opencloud_full/.env
- services/storage-users/README.md
Removes or fixes a couple of invalid links to documentation
> Clean invalid documentation links

- services/storage-users/pkg/command/uploads.go
>  fix cli driver initialization for "posix" 

- .make/go.mk
- opencloud/Makefile
- opencloud/docker/Dockerfile.linux.debug.arm64
Fix debug docker make step.
- test case 1:
- test case 2:
- ...
> fix: add missing debug docker

- opencloud/docker/Dockerfile.linux.amd64
- opencloud/docker/Dockerfile.linux.arm64
- opencloud/docker/Dockerfile.linux.debug.amd64
- opencloud/docker/Dockerfile.multiarch
- test case 1:
- test case 2:
- ...
> chore: update alpine to 3.21

- opencloud/docker/Dockerfile.linux.amd64
- opencloud/docker/Dockerfile.linux.arm64
- opencloud/docker/Dockerfile.linux.debug.amd64
- opencloud/docker/Dockerfile.linux.debug.arm64
- opencloud/docker/Dockerfile.multiarch
> Fix permission errors when uploading a new instance logo

- .woodpecker.env
- services/web/Makefile
Update web to `v2.1.0`. See https://github.com/opencloud-eu/web/releases/tag/v2.1.0 for details.
- Works towards https://github.com/opencloud-eu/opencloud/issues/458
> [full-ci] chore(web): update web to v2.1.0

- deployments/examples/opencloud_full/.env
a micro fix
- test case 1:
- test case 2:
- ...
> fix tiny typo

- .github/workflows/labels.yml
Add label checker workflow.
- test case 1:
- test case 2:
- ...
> add label checker

- services/web/assets/themes/opencloud/theme.json
- test case 1:
- test case 2:
- ...
> feat: change theme.json primary color

- .make/go.mk
- pkg/version/version.go
Fix the daily version in the build.
Before `OpenCloud 0.0.0`
After `OpenCloud 2.0.0+4d53af7d6`
- test case 1:
- test case 2:
- ...
> fix: correct daily version

- deployments/examples/opencloud_full/.env
- test case 1:
- test case 2:
- ...
> fix: traefik credentials

- deployments/examples/opencloud_full/.env
- test case 1:
- test case 2:
- ...
> fix: full deployment tika description is wrong

- .woodpecker.env
- services/web/Makefile
Updating web to v2.2.0 for the upcoming rolling release.
> [full-ci] chore(web): bump web to v2.2.0

- .woodpecker.star
delete variables that are not needed or used
- part of https://github.com/opencloud-eu/qa/issues/46
clean code
:robot:
> [full-ci] remove unneeded variables

- .woodpecker.star
Delete some parentheses that my IDE thinks are unneeded
On top of #591 - to reduce risk of conflicts, so only review the last commit
just some clean up
:wood:-:pick:  (:bird:)
> [full-ci] Remove unneeded parentheses

- docs/20-web/50-extension-system/index.md
- test case 1:
- test case 2:
- ...
> fix: web dev docs broken links

- .woodpecker.star
related https://github.com/opencloud-eu/opencloud/issues/645
before: 
after:
> Check that clamav is ready before the server run

- tests/README.md
- tests/acceptance/run_api_tests.sh
> update test docs

- .woodpecker.star
This PR store events in object and use it whenever need 
- https://github.com/opencloud-eu/qa/issues/42
- CI
> [full-ci]Remove code duplication from starlark

- deployments/examples/opencloud_full/keycloak.yml
> fix deployment: do not create demo accounts when using keycloak

- .woodpecker.star
clean up things that we don't need
part of https://github.com/opencloud-eu/qa/issues/46
:robot:
> [full-ci] delete unneeded containers and directories

- services/storage-users/pkg/config/config.go
- services/storage-users/pkg/config/defaults/defaultconfig.go
- services/storage-users/pkg/revaconfig/drivers.go
Depends on https://github.com/opencloud-eu/reva/pull/155
> Add env var to make the inotify stats frequency configurable

- .github/workflows/labels.yml
- test case 1:
- test case 2:
- ...
> fix: labels bot needs token for forks

- .woodpecker.star
Fix the missing version in the binary release steps.
Needs to be backported to `stable-2.0`
- test case 1:
- test case 2:
- ...
> fix: binary release version

- services/storage-users/pkg/config/defaults/defaultconfig.go
> fix(decomposeds3): enable async-uploads by default (#686)

- .woodpecker.star
> fix: binary release version 

- deployments/examples/opencloud_full/.env
- test case 1:
- test case 2:
- ...
> Update descirption of COLLABORA_SSL_ENABLE

- pkg/version/version.go
- test case 1:
- test case 2:
- ...
> chore: prepare release, bump version

- .woodpecker.env
- services/web/Makefile
See here for changelog: https://github.com/opencloud-eu/web/releases/tag/v2.3.0
> [full-ci] chore(web): bump web to v2.3.0

- services/idp/src/app.css
- services/idp/src/components/ResponsiveScreen.jsx
- test case 1:
- test case 2:
- ...
> fix: idp login logo url exceeds logo

- services/idp/pkg/config/defaults/defaultconfig.go
- test case 1:
- test case 2:
- ...
> feat: set idp logo defaul url

- .woodpecker.star
- tests/acceptance/TestHelpers/CliHelper.php
- tests/acceptance/bootstrap/CliContext.php
- tests/acceptance/config/behat.yml
- tests/acceptance/docker/Makefile
- tests/acceptance/docker/src/opencloud-base.yml
- tests/acceptance/docker/src/opencloud.Dockerfile
- tests/acceptance/docker/src/posix.yml
- tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
- tests/ocwrapper/opencloud/opencloud.go
- tests/ocwrapper/wrapper/handlers/handler.go
first collaborative posix test. 
- The admin user creates a folder in the file system, and the Alice user can see that folder in their personal space
> collaborative posix test

- .woodpecker.star
- tests/acceptance/bootstrap/CliContext.php
- tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
I've added a test for basic file actions on the file system:
> collaboration posix tests

- tests/acceptance/features/apiSpaces/changeSpaces.feature
> [test-only] test for #452

- deployments/examples/opencloud_full/.env
- deployments/examples/opencloud_full/opencloud.yml
- services/idp/src/containers/Login/Login.jsx
- test case 1:
- test case 2:
- ...
> chore: add idp login text setting to full deployment example

- .woodpecker.star
When I change only the files in the `tests` folder. e.g. add some tests -> tests in CI do not run
> do not skip test on the build binary step

- deployments/examples/opencloud_full/collabora.yml
- services/collaboration/pkg/service/grpc/v0/service.go
- services/collaboration/pkg/service/grpc/v0/service_test.go
- tests/acceptance/features/apiCollaboration/wopi.feature
Hiding the close button in collabora via https://sdk.collaboraonline.com/docs/advanced_integration.html#url-query-parameters
- Fixes https://github.com/opencloud-eu/web/issues/458
- Fixes https://github.com/opencloud-eu/web/issues/459
- test case 1:
- test case 2:
- ...
> feat: hide close button in collabora

- .woodpecker.env
- services/web/Makefile
> [full-ci] chore: bump web to v3.0.0-alpha.1

- tests/acceptance/TestHelpers/GraphHelper.php
- tests/acceptance/bootstrap/SharingNgContext.php
- tests/acceptance/features/apiSharingNg1/listPermissions.feature
related #916
select filter for: 
- `drives/$spaceId/root/permissions`
- `drives/$spaceId/items/$itemId/permissions`
endpoints
> apiTest. select option for root/permissions endpoint

- services/graph/pkg/service/v0/api_driveitem_permissions.go
- services/graph/pkg/service/v0/api_driveitem_permissions_test.go
This allows to exclude public links from the request results.
Related Issue #485
> graph: Add $filter to only list (and/or count) member permissions

- services/web/README.md
> fix(docs): WEB_ASSET_PATH was still mentioned in the web readme

- services/web/assets/themes/opencloud-dev/theme.json
- services/web/assets/themes/opencloud/theme.json
- Part of https://github.com/opencloud-eu/web/issues/858
- test case 1:
- test case 2:
- ...
> feat: add accessibility url to theme.json files

- .woodpecker.star
port #1053 and [e8a1609bde5f2587482372774b51dcad9df0e8d6](https://github.com/opencloud-eu/opencloud/commit/e8a1609bde5f2587482372774b51dcad9df0e8d6) to stable-2.0
> get hostname of S3 server from var. not secret

- go.mod
- go.sum
- vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/trashbin/trashbin.go
- vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/assimilation.go
- vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/tree.go
- vendor/github.com/opencloud-eu/reva/v2/pkg/storage/utils/templates/templates.go
- vendor/modules.txt
part of the https://github.com/opencloud-eu/opencloud/issues/1254
> [full-ci] Reva bump 2.35.0

- .woodpecker.env
- services/web/Makefile
Bumps web to v3.2.0 for the upcoming rolling release.
> [full-ci] chore: bump web to v3.2.0

- .woodpecker.star
do nightly CI runs
part of https://github.com/opencloud-eu/qa/issues/41
> run CI on cron jobs

- .woodpecker.star
I forgot to add the cron setting in this place. Hopefully this will now run all pipelines and with that also run the notification at the end.
> run also e2e-tests-multi-service pipeline on cron

- .woodpecker.star
run API, CLI & webUI tests additionally with `STORAGE_USES_POSIX_WATCH_FS` enabled if PR title has `full-ci` or when the job is run with cron
- Fixes #1358
make sure  `STORAGE_USES_POSIX_WATCH_FS` works correctly
:robot:
> [full-ci] run tests with STORAGE_USES_POSIX_WATCH_FS

- docs/adr/0002-use-education-api-for-multitenant-user-provisioning.md
@butonic @micbar This is trying to summarize what we discussed last week around the provisioning API for multi-tenancy.
Please comment.
> adr: use eduation api for multi-tenancy provisioning

- tests/acceptance/TestHelpers/GraphHelper.php
- tests/acceptance/features/apiContract/sharesReport.feature
- tests/acceptance/features/apiSharingNg1/sharedByMe.feature
- tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
related https://github.com/opencloud-eu/opencloud/pull/1257
> check thumbnails in the share with me response
