opencloud-eu/opencloud

services/web/pkg/theme/service.go
Logo upload broke when we changed the theme scheme, see https://github.com/opencloud-eu/opencloud/pull/165 and https://github.com/opencloud-eu/web/pull/40
Just needed to update some keys for making the logo upload and reset work again.
- Fixes https://github.com/opencloud-eu/opencloud/issues/203
- ✋
=> fix(web): logo upload

deployments/continuous-deployment-config/opencloud_full/master.yml, deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/collabora.yml, deployments/examples/opencloud_full/onlyoffice.yml, deployments/examples/opencloud_full/opencloud.yml, opencloud/Makefile, opencloud/docker/manifest-latest.tmpl, opencloud/docker/manifest.production-latest.tmpl, opencloud/docker/manifest.production.tmpl, opencloud/docker/manifest.tmpl
Docker images live in the org namespace `opencloudeu` since `-` is not an allowed char on docker hub. Hope I found all the occurrences.
=> fix: docker image names

deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/collabora.yml, deployments/examples/opencloud_full/onlyoffice.yml, deployments/examples/opencloud_full/opencloud.yml
related: https://github.com/opencloud-eu/opencloud/issues/257
We can't run `opencloud full` if we don't have `opencloudeu/opencloud:latest` https://hub.docker.com/r/opencloudeu/opencloud
```
% docker compose up -d  
[+] Running 2/2
✘ collaboration Error context canceled                                                                                               1.0s 
✘ opencloud Error     failed to resolve reference "docker.io/opencloudeu/opencloud:latest": docker.io/opencloude...                  1.0s 
Error response from daemon: failed to resolve reference "docker.io/opencloudeu/opencloud:latest": docker.io/opencloudeu/opencloud:latest: not found
```
using opencloudeu/opencloud-rolling:latest instead
=> use opencloud rolling image in the full example

.make/go.mk, opencloud/docker/Dockerfile.linux.multiarch
related: https://github.com/opencloud-eu/opencloud/pull/229/commits/7c1acbcd48793e2785a47ae52f885297cb7d77cf
while `opencloud` build I got this error: 
```
make -C opencloud build              
go build -v -tags 'disable_crypt' -ldflags '-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn -s -w -X "github.com/opencloud-eu/opencloud/pkg/version.String=" -X "github.com/opencloud-eu/opencloud/pkg/version.Tag=1.0.0" -X "github.com/opencloud-eu/opencloud/pkg/version.Date=20250226" -X "github.com/opencloud-eu/opencloud/pkg/config/defaults.BaseDataPathType=path" -X "github.com/opencloud-eu/opencloud/pkg/config/defaults.BaseDataPathValue=/var/lib/opencloud" -X "github.com/opencloud-eu/opencloud/pkg/config/defaults.BaseConfigPathType=path" -X …
```
=> static binary issue

tests/acceptance/docker/Makefile, tests/acceptance/docker/src/opencloud.Dockerfile, tests/acceptance/docker/src/posix.yml
this allows running
```
❯ make -C opencloud dev-docker
❯ STORAGE_DRIVER=posix LOCAL_TEST=true ./tests/acceptance/run_api_tests.sh
make: Verzeichnis „/home/jfd/Repositories/opencloud/tests/acceptance/docker“ wird betreten
Build and start server...
COMPOSE_FILE=src/opencloud-base.yml:src/tika.yml:src/email.yml:src/posix.yml \
COMPOSE_PROJECT_NAME=opencloud-acceptance-tests \
OC_IMAGE_TAG=dev \
WITH_WRAPPER=true \
TEST_SOURCE=opencloud \
STORAGE_DRIVER=posix \
OC_ASYNC_UPLOADS=true \
SEARCH_EXTRACTOR_TYPE=tika \
OC_ADD_RUN_SERVICES=notifications \
docker compose up -d --build --force-recreate
WARN[0000] The "POSTPROCESSING_STEPS" variable is not set. Defaulting to a blank string. 
Compose now can delegate build to bake for better performances
Just set COMPOSE_BAKE=true
[+] Building 0.9s …
```
=> allow running api tests with posix

tests/README.md, tests/acceptance/bootstrap/OcConfigContext.php, tests/acceptance/docker/Makefile, tests/acceptance/docker/src/run-tests.sh, tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature, tests/acceptance/features/apiSharingNgLinkSharePermission/updateLinkShare.feature, tests/acceptance/run_api_tests.sh
- set correct path if you run local-test with opencloud-docker-server 
OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST="/drone/src/tests/config/drone/banned-password-list.txt"
- add command to make file to run test with posix storage
```
BEHAT_FEATURE='tests/acceptance/features/apiSharingNgLinkShareRoot/createLinkShare.feature' \      
make -C tests/acceptance/docker test-opencloud-feature-posix-storage 
```
or just run apiGraph suite with posix  `make -C tests/acceptance/docker localApiTests-apiGraph-posix`
=> fix test with password banned list. add run test with posixfs

README.md
Fixing docs link in readme, as mentioned here https://github.com/opencloud-eu/opencloud/issues/242#issuecomment-2691389236
=> fix: docs link in readme

.make/default.mk, opencloud/Makefile
i introduced a recursive make call (make go-generate) in https://github.com/opencloud-eu/opencloud/pull/278, beside that generation assets in ./opencloud (make generate) failed too.
```bash
make -C opencloud generate build
```
- Fixes https://github.com/opencloud-eu/opencloud/issues/315
- reproduced locally
=> fix: make recursion and missing opencloud node generate step

pkg/crypto/gencert.go, pkg/l10n/l10n.go, pkg/tracing/tracing.go, services/notifications/pkg/email/composer.go, services/search/pkg/service/grpc/v0/service.go, services/settings/pkg/service/v0/service.go, services/thumbnails/pkg/service/grpc/v0/service.go, services/userlog/pkg/service/conversion.go
Go 1.24 does some stricter checks now on arguments to functions accepting format strings.
This commit fixes a couple of "non-constant format string in call to ..." errors when running the unit tests.
=> Fix build with go 1.24

opencloud/Makefile
$OC_HOME/opencloud/Makefile contains `node-generate-prod` which is called by `node-generate-dev` (`*-dev` calls `*-prod` if undefined) which then calls all `*-prod` in each service... which overwrites the assets in web.
sounds complicated which it isnt, `porp ™` (a plain old recursion problem) 🤣 , we have multiple ways to fix it:
1. remove the fallback `*-prod` if no `*-dev` step is defined
1. remove the `node-generate-prod` loop in $OC_HOME/opencloud/Makefile
i decided for NR. 2 because I still think it is practical to have that fallback.
=> fix: make re-build node artifacts

services/storage-users/pkg/config/defaults/defaultconfig.go
This avoids loosing the user's personal space after renaming the user.
Closes: #192
=> posixfs: Use userid as the foldername for personal space

.woodpecker.star, tests/config/woodpecker/check_go_bin_cache.sh, tests/config/woodpecker/check_web_cache.sh
The web and Go-bingo cache was never found because the bucket is not publicly available and we checked the existence of the cache just with a `curl` request to the public URL.
Now the cache is checked using `mc` and the correct access_id and access_secret
Because woodpecker does not have a custom exit code to skip the following steps without failing them, I'm just writing the result into an env file and reading it in every step that follows.
The pnpm store cache was not working because the filename to write the cache was `pnpm-store.tar.gz` but when checking it trying to restore we used `web-pnpm.tar.gz`
- part of https://github.com/opencloud-eu/qa/issues/1
save :timer_clock: 
save :earth_asia: 
:robot:
=> fix cache in CI

.woodpecker.env, services/web/Makefile
See https://github.com/opencloud-eu/web/releases/tag/v2.0.0 for a full list of changes.
=> chore: bump web to v2.0.0

services/idp/pkg/config/config.go, services/idp/pkg/config/defaults/defaultconfig.go
The default IDP configuration in services/idp/pkg/config/defaults/defaultconfig.go doesn't include post_logout_redirect_uris for iOS and Android clients. This creates issues with the logout process in mobile applications, as they can't properly redirect after logout.
This fixes it, based on the ideas of @michaelstingl
- Fixes #367 
- test case 1:
- test case 2:
- ...
=> feat: add post logout redirect uris for mobile clients

.woodpecker.star, tests/acceptance/expected-failures-API-on-decomposed-storage.md
Enable the tests coming from oC10 times
- part of https://github.com/opencloud-eu/qa/issues/1
:robot:
=> enable main API test suite to run in CI

services/frontend/pkg/config/defaults/defaultconfig.go, services/frontend/pkg/revaconfig/config.go, services/ocdav/pkg/config/defaults/defaultconfig.go
Clears the `edition` fallback on "Community" in the capabilities. We want to have this as empty string without any fallback.
closes https://github.com/opencloud-eu/opencloud/issues/392
=> feat: clear edition fallback

.woodpecker.star
The 'exclude' feature
(https://woodpecker-ci.org/docs/usage/workflow-syntax#path) does not seem to provide # what we need. It seems to skip the build as soon as one of the changed files matches an exclude pattern, we only # want to skip of ALL changed files match. So skip this condition for now:
This should just be a temporary fix until we figured out what's wrong with the `when` conditions. (See #438 )
=> Disable the 'exclude' patterns on the path conditional for now

opencloud/Makefile
Fixed the dockerhub org name in the multiarch dev build image name... not very high priority, since the CI seems to build differently?!
=> fix: org name in multiarch dev build

services/storage-users/pkg/command/uploads.go
When started with the '--resume' command line switch the 'storage-users uploads sessions' was crashing because it did not initialize the event queue correctly.
Fixes: #390
=> fix(storage-users): 'uploads sessions' command crash

deployments/examples/bare-metal-simple/install.sh
Bumped version manually. Would be good to find a way to somehow automatically jump to the latest version.
=> Bump opencloud version in bare-metal-simple script

deployments/examples/opencloud_full/collabora.yml
Bumps Collabora in the deployment example to `24.04.13.2.1` and fixes the entrypoint. It seems to have changed with newer versions of the docker image, hence we need to specify the entrypoint manually to make the start commands work.
=> chore: bump Collabora in deployment example and fix entrypoint

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
Addresses CVE-2025-30204
Closes: #482
=> Bump golang-jwt/jwt/v4 to 4.5.2

tests/acceptance/expected-failures-API-on-decomposed-storage.md, tests/acceptance/expected-failures-API-on-posix-storage.md, tests/acceptance/features/coreApiVersions/fileVersions.feature, tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
This PR remove closed PR and add new related issue on expected failure file
Tests have been updated according to current behaviour. 
**Note**-multiple file version will be created for multiple file upload with same mtime 
- Part of https://github.com/opencloud-eu/opencloud/issues/391
- https://github.com/opencloud-eu/opencloud/issues/468
-
=> [full-ci]Remove mtime 500 issue from expected failure

tests/acceptance/expected-failures-without-remotephp.md
This test somehow was missing in the list, but fails for the same reason. It was not discovered because we do not run `full-ci` very frequently
fix `full-ci` runs
:robot:
=> [full-ci] add one more TUS test to expected to fail file

services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_test.go, services/graph/pkg/service/v0/base.go, services/graph/pkg/service/v0/rolemanagement.go, services/graph/pkg/service/v0/service.go, services/graph/pkg/service/v0/sharedwithme.go
While investigating https://github.com/opencloud-eu/opencloud/issues/485 I noticed that we are constantly allocating memory to build the list of available roles. This PR changes this to be done once at startup.
This does not fix the PR mentioned above. It is just something I noticed while trying to find out where all the GetUser requests are coming from. 
cc @fschade
=> graph: reduce memory allocations

deployments/examples/opencloud_full/keycloak.yml
https://github.com/opencloud-eu/opencloud/pull/465#issuecomment-2765385244
fix problem when we use `KEYCLOAK_DOMAIN` != `keycloak.opencloud.test` in the `.env`  
how to test: 
- enable `keycloack.yml` in the `.env` of the `opencloud_full` 
- set `KEYCLOAK_DOMAIN=newkeycloak.opencloud.test`
- start `opencloud` `docker compose up -d`
- open [cloud](https://cloud.opencloud.test/) in the browser
Actual: works fine
=> fix keycloak example #465

deployments/examples/opencloud_full/web_extensions/unzip.yml
Bumps the unzip extension in the opencloud deployment example to `v1.0.2`.
=> chore: bump unzip extension to v1.0.2

.woodpecker.star
This reverts commit 1a54b4ce90c9d4451464b5b0d63e5c8f25e43f60. The exclude feature has been fixed in woodpecker 3.5.0
Partial fixes: https://github.com/opencloud-eu/qa/issues/37
=> Revert "Disable the 'exclude' patterns on the path conditional for now"

tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md, tests/acceptance/features/apiAntivirus/antivirus.feature
The server returns the correct string, but the test expectation is wrong
reduce expected-to-fail lines
:robot:
=> [full-ci] fix expected spanish string in test

deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/clamav.yml, services/antivirus/README.md, services/antivirus/pkg/command/server.go, services/antivirus/pkg/config/config.go, services/antivirus/pkg/config/defaults/defaultconfig.go, services/antivirus/pkg/scanners/clamav.go, services/antivirus/pkg/scanners/clamav_test.go, services/antivirus/pkg/scanners/scanners.go, services/antivirus/pkg/service/service.go
This pull request introduces a partial mode for antivirus scanning to handle large files efficiently.
- Inspired by [opencloud-eu/opencloud#529](https://github.com/opencloud-eu/opencloud/issues/529#issuecomment-2768923084)
This pull request depends on the following PR being merged first:
- [opencloud-eu/reva#153](https://github.com/opencloud-eu/reva/pull/153)
This change is required to enhance the antivirus scanning efficiency for large files. The partial mode allows handling large files by scanning parts rather than loading the entire file.
=> feat(antivirus): add partial scanning mode

.woodpecker.star
only use the wrapper in the tests if needed, otherwise just run opencloud binary by itself
- Fixes https://github.com/opencloud-eu/opencloud/issues/408
make the function do what it promises
:wood: - :pick: (:bird:)
=> [full-ci] only use wrapper when requested

pkg/version/version.go
=> chore: bump version to v2.1.0

deployments/examples/opencloud_full/.env
Improve the description about the storage path in the .env. Add that the data directories are owned by the user and group with ID 1000:1000
- Fixes [docs issue](https://github.com/opencloud-eu/docs/issues/195)
Help user to run into permission issues.
tested with our docker compose full setup
=> feat: improve the info about storage path in deployment example

.woodpecker.env, services/web/Makefile
See changelog: https://github.com/opencloud-eu/web/releases/tag/v2.1.1
=> [full-ci] chore(web): bump web to v2.1.1

deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/clamav.yml, services/antivirus/README.md, services/antivirus/pkg/config/config.go
The current full example Docker deployment lacks a maximum scan size when the virus scanner is enabled. As a result, all files are scanned regardless of size. However, since Clamav has limits set in the default setup, this combination results in orphaned files that get stuck in post-processing.
The problem has already been fixed in the current main branch. Since an additional scan mode has been integrated here, a full backport is not possible. Therefore, I have only fixed the bare minimum to resolve the bug in these installations.
- Backports parts of https://github.com/opencloud-eu/opencloud/pull/559
- Issue  https://github.com/opencloud-eu/opencloud/issues/529
Quite simply, the basic installation from our example deployment should run error-free out of the box
- local test deployment
=> fix(antivirus | backport): introduce a default max scan size for the full example deployment

deployments/examples/bare-metal-simple/README.md, deployments/examples/bare-metal-simple/install.sh
The quick install.sh has hardcoded paths.
This feature adds an option to set (both!) config and data to some specified parent directory as well as the hostname of the server.
Simplifies testing with different back end storages.
Locally and on remote servers
Manually
=> Feat: install.sh now honors OC_BASE_DIR and OC_HOST

deployments/examples/opencloud_full/config/opencloud/app-registry.yaml
The app provider is called `CollaboraOnline` in the deployment example, not `Collabora`. Also switches the default app to Collabora for all mime types since it's the only app provider running per default.
fixes https://github.com/opencloud-eu/opencloud/issues/691
=> chore: fix app provider default names in opencloud_full deployment

.github/workflows/labels.yml, deployments/examples/opencloud_full/README.md
Update the links in the opencloud_full deployment example README to point to the correct documentation URLs.
- Fixes #621
The links in the README were outdated and returning 404 errors. This PR updates the links to point to the current documentation structure.
- test environment: Local documentation links were verified to work
- test case 1: Checked that the links point to valid pages in the documentation
=> Fix broken links in opencloud_full README.md

deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/config/keycloak/opencloud-realm.dist.json, deployments/examples/opencloud_full/ldap.yml
This PR improves the authentication system with better LDAP and Keycloak configurations for both autoprovisioning and shared user directory modes. It enhances the default deployment examples with clearer documentation and more standardized configuration.
- Simplify LDAP schema by using standard LDAP attributes rather than custom objectClasses
- Configure LDAP as read-only from OpenCloud's perspective by default
- Switch to using `entryUUID` as the standard user/group identifier
- Add comprehensive documentation in .env file explaining the LDAP configuration
- (optional) use writable sub tree for custom groups
- Add support for two distinct authentication modes:
1. **Autoprovisioning**: Users are managed by Keycloak and auto-created in OpenCloud on first login
2. **Shared User Directory**: …
=> Supported production setup with Keycloak and LDAP

pkg/middleware/account.go, services/activitylog/pkg/service/http.go, services/auth-app/pkg/service/service.go, services/graph/pkg/middleware/auth.go, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/middleware/account_resolver.go, services/proxy/pkg/middleware/account_resolver_test.go, services/proxy/pkg/middleware/app_auth.go, services/proxy/pkg/middleware/app_auth_test.go, services/proxy/pkg/middleware/authentication_test.go, services/proxy/pkg/middleware/create_home.go, services/proxy/pkg/middleware/public_share_auth.go, services/proxy/pkg/middleware/public_share_auth_test.go, services/proxy/pkg/router/router.go
This introduces the "additional_headers", "remote_user_header" and
"skip_x_access_token" config keys to allow configuring routes to
external services that require addtional headers to be set.
"remote_user_header": defines the name of a Header that will carry the
userid of the authenticated user on the outgoing request.
"additional_headers": defines a list of header names and values that will
be added to outgoing requests on matching routes.
"skip_x_access_token": when set to true the reva access token will not
be added to the outgoing request.
This is the groundwork for #206 I'll submit required `opencloud_full` adjustments in a separate PR.
=> proxy(router): Allow to set some outgoing headers

deployments/examples/opencloud_full/.env, deployments/examples/opencloud_full/config/opencloud/proxy.yaml, deployments/examples/opencloud_full/config/radicale/config, deployments/examples/opencloud_full/radicale.yml
This adds another piece for: #206 
To enable radicale:
* uncomment the `#RADICALE=:radicale.yml` line in `.env` and deploy
* Generate an App Token
* point your caldav and carddav clients to `https://your.cloud.name/caldav` (the proxy is also forwarding `https://your.cloud.name/carddav`, technically it shouldn't matter which one is used)
Radicale is currently configured to add a default Calendar and Addressbook for every user that logs in. So that most clients should work out of the box.
For enabling the radicale WebUI e.g. to import a calendar or address books, see the notes in the proxy.yaml file.
=> deployment: Adapt opencloud_full to include radicale

.woodpecker.star, tests/acceptance/expected-failures-localAPI-on-posix-storage.md
- we need to set `[decomposed]` to the title to run tests with decomposed storage - checked that it works
- by default we run posix. But CliCommand always uses decomposed. I changed title in CI
- localApiTests used `expected-failures-localAPI-on-decomposed-storage.md`. Fixed it
=> run ci with decomposed

services/nats/pkg/command/server.go, services/nats/pkg/server/nats/nats.go
Only enable trace and/or debug logging when the outer logger has the log level set accordingly. Even when the though the messages where not really logged the nats service wasted quite some cycles especially in the trace log related code path.
Related issue: #716
For details see: https://github.com/opencloud-eu/opencloud/issues/716#issuecomment-2866835467
=> nats: Don't enable debug and trace logging by default

tests/acceptance/bootstrap/CliContext.php, tests/acceptance/config/behat.yml, tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
tests for: 
- rename file on POSIX filesystem
- checking that file versions are still up to date after renaming or changing the contents of a file in a POSIX file system
- checking that share and public link still up to date after renaming or changing the contents of a file in a POSIX file system
=> PosixTest. Check that version, share and link still exist

.woodpecker.star
we always run pipelines in the release PR (changelog.md is changed). example https://ci.opencloud.eu/repos/3/pipeline/1633
- `checkGherkink-standart`, `checkStarlark`, `check-expected-failures`, `web-cache` didn't have an exception path, so it always ran
=> unnecessary pipeline run in the release ticket

.woodpecker.env, services/web/Makefile
Bumps web version to v2.4.0 for the upcoming rolling release.
se changelog here: https://github.com/opencloud-eu/web/pull/603
=> [full-ci] chore(web): bump web to v2.3.0

services/graph/mocks/drive_item_permissions_provider.go, services/graph/pkg/service/v0/api_driveitem_permissions.go, services/graph/pkg/service/v0/api_driveitem_permissions_test.go, services/graph/pkg/service/v0/utils.go
This add the possibility to `$select` on `@libre.graph.permissions.actions.allowedValues`.
The request:
`GET /drives/<driveid>/root/permissions?$select=@libre.graph.permissions.actions.allowedValues`
can be used to figure out what permissions the requesting user has on a specific space (e.g. when deciding which action to display in the context menu)
Related Issue #485
=> graph: Add more $select options to ListPermissions endpoint

pkg/storage/metadata/lazy.go, pkg/storage/storage.go, services/graph/pkg/server/http/server.go, services/graph/pkg/service/v0/api_users_user_profile_photo.go, services/graph/pkg/service/v0/api_users_user_profile_photo_test.go, services/graph/pkg/service/v0/application_test.go, services/graph/pkg/service/v0/approleassignments_test.go, services/graph/pkg/service/v0/driveitems_test.go, services/graph/pkg/service/v0/educationclasses_test.go, services/graph/pkg/service/v0/educationschools_test.go, services/graph/pkg/service/v0/educationuser_test.go, services/graph/pkg/service/v0/graph_test.go, services/graph/pkg/service/v0/groups_test.go, services/graph/pkg/service/v0/option.go, services/graph/pkg/service/v0/password_test.go, services/graph/pkg/service/v0/service.go, services/graph/pkg/service/v0/sharedbyme_test.go, services/graph/pkg/service/v0/sharedwithme_test.go, services/graph/pkg/service/v0/users_test.go
The recently introduced profile photo graph api (https://github.com/opencloud-eu/opencloud/pull/864) failed to initialize every now and then if the storage is not ready yet as pointed out in https://github.com/opencloud-eu/opencloud/issues/944#issuecomment-2911996712. 
Beside that i also made a wrong design decision which made testing unnecessary hard, both is fixed in this PR.
- Extends: https://github.com/opencloud-eu/opencloud/pull/864
- Fixes: https://github.com/opencloud-eu/opencloud/issues/944#issuecomment-2911996712
=> fix(graph-metadata): lazy cs3 metadata storage initialization

services/webdav/pkg/config/defaults/defaultconfig.go, services/webdav/pkg/service/v0/search.go
Add the oc:privatelink field to the webdav search response.
- Fixes https://github.com/opencloud-eu/opencloud/issues/971
consistency, TBH... someone has to help me to understand why we have a description and the Motivation and Context section, i don't get it.. i always struggle with that... but only if YOU read that... :) 
- web client
=> Enhancement: Introduced support for PrivateLink in WebDAV search responses

pkg/version/version.go
- run all tests on decomposed storage
- bump v3.0.0 version for upcoming rolling release
=> [decomposed] bump-version-v3.0.0

services/proxy/pkg/middleware/account_resolver.go
After autoprovisioning a user, we need to get a reva token via `auth-machine`. If that fails the code would panic because the logger tried to access the `user` object returned from the GetUserByClaims call. Which is `nil`in case failure.
Fixes #936
=> fix(proxy): Prevent panic when autoprovsioning user

CONTRIBUTING.md
The CONTRIBUTING.md file links to the developers documentation but the current URLs seem to refer to an old documentation, since they now link to an 404 error page. I updated the links to the current doucmentation page.
- Fixes #1076 
The links refer to an old address.
Manual test in my browser.
=> Update the href of CONTRIBUTING to the dev docs

services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
Coming from Matrix chat:
```
Hey everyone, I noticed that Collabora CODE gets it's UI language from the Opencloud user's language setting. However, there is only one English there which defaults to US. As a result, CODE shows imperial metrics (e.g. for page margin). Is there a way to switch to UK or Australian English so that I can use CODE with an English UI but with metric units?
```
Before **(Look to the right 👀 )**
After
- test case 1:
- test case 2:
- ...
=> fix: collabora use metrics instead of imperial metric system

services/collaboration/pkg/connector/fileconnector.go, services/collaboration/pkg/connector/fileconnector_test.go, services/collaboration/pkg/connector/fileinfo/collabora.go, tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Re-enable the `Save As` and `Export` buttons in the Collabora ui.
Needed for https://github.com/opencloud-eu/web/issues/708 and https://github.com/opencloud-eu/web/issues/422
=> feat: re-enable Save As and Export in collabora

pkg/version/version.go
- run all tests on decomposed storage
- bump v3.1.0 version for upcoming rolling release
=> [decomposed] bump-version-v3.1.0

services/collaboration/pkg/command/server.go, services/collaboration/pkg/config/cs3api.go, services/collaboration/pkg/config/defaults/defaultconfig.go
App providers only register on startup of the collaboration service, this can lead to information loss if open-cloud (app-provider) goes down. The solution is fairly simple, i would LOVE to see an implementation which uses a registry instead... 
- Fixes https://github.com/opencloud-eu/opencloud/issues/616
- docker deployment
=> fix(collaboration): re register app providers in a configurable interval

.woodpecker.star
Fix our docker build. This change has been triggered by that breaking change in https://codeberg.org/woodpecker-plugins/docker-buildx/pulls/229/
- test case 1:
- test case 2:
- ...
=> fix: build args are now an object

.woodpecker.star
The CI is currently failing because of the starlark linter: https://ci.opencloud.eu/repos/3/pipeline/2268/270
The problem was introduced with: https://github.com/opencloud-eu/opencloud/pull/1215/files#diff-0d2cb487e7e8bfe77cea5a2347a1987e5c8864b49ffdc1a75543dba849928a74R2195
Not sure why the CI didn't pick it up back then.
This should fix it.
=> Adjust .woodpecker.star to make linter happy

Makefile, protogen/Makefile
This PR reverts #1187 and adds a NOOP clean  step to `protogen/Makefile`
=> revert #1187  and add a NOOP clean  step to `protogen/Makefile`

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `2.0.4` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `stable-2.0` this pull-request will be updated.
- [Backport] fix: build_args is now an object [[#1213](https://github.com/opencloud-eu/opencloud/pull/1213)]
=> 🎉 Release 2.0.4

tests/acceptance/bootstrap/SharingNgContext.php, tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
The expirationDate for new shares needs to be in the future. Using static dates in the tests means we need to update them every now an then. This adjusts the helpers to allow relative date formats like "+3 days" and "tomorrow" when creating shares.
=> tests: Avoid static dates when creating shares

services/ocdav/pkg/command/server.go, services/ocdav/pkg/config/config.go, services/proxy/pkg/command/server.go, services/proxy/pkg/config/config.go, services/proxy/pkg/middleware/signed_url_auth.go, services/proxy/pkg/middleware/signed_url_auth_test.go
With the ocdav service being able to provided signed download URLs we need the proxy to be able to verify the signatures.
This should also be a first step towards phasing out the weird ocs based client side signed urls.
Related Tickets: https://github.com/opencloud-eu/opencloud/issues/1104
This is still a bit of a PoC, but should be good enough for providing allowing some traction on: https://github.com/opencloud-eu/web/issues/704
Unfortunately in its current form it is a breaking change (a new configuration key is required) and would require a major version bump again. I'd be interested in suggestions about how we can make this non-breaking in a simple way.
To use this the new config variable `OC_URL_SIGNING_SHARED_SECRET` needs to be set. (Just use some randon string content)
=> proxy(sign_url_auth): Allow to verify server signed URLs

pkg/version/version.go
- run all tests on decomposed storage
- bump v3.3.0 version for upcoming rolling release
=> [decomposed] bump-version-v3.3.0

services/web/pkg/config/options.go
As of https://github.com/opencloud-eu/web/pull/1081 (need to bump web in opencloud though for this PR to have any effect) we have a `defaultAppId` option for the config.json, which allows to specify a different app than `files` (which is the default in web code base).
Allow users to e.g. start with a link collection from the external sites app as their main entry point.
=> feat: add defaultAppId option for the web config.json

services/storage-users/pkg/config/defaults/defaultconfig.go
The STORAGE_USERS_DATA_GATEWAY_URL env var is used in the `tokens` `datagateway_endpoint` reva configuration. That `DataGatewayEndpoint` is used by the decomposedfs driver to create urls:
```go
// URL returns a url to download an upload
func (session *DecomposedFsSession) URL(_ context.Context) (string, error) {
// [ ... ]
return joinurl(session.store.tknopts.DataGatewayEndpoint, tkn), nil
}
```
As the comment points out this URL is internally used when emitting events. Either in:
```go
func (session *DecomposedFsSession) FinishUploadDecomposed(ctx context.Context) error {
// [ ... ]
s, err := session.URL(ctx)
if err != nil {
return err
}
var iu *userpb.User
if utils.ExistsInOpaque(u.Opaque, "impersonating-user") {
iu = &userpb.User{}
if err := utils.ReadJSONFromOpaque(u.Opaque, …
```
=> directly connect to frontend

.woodpecker.star
This PR adds pipelines to purge following caches:
- Browsers cache
- Opencloud web build cache
- Playwright tracing cache
Check this [Build](https://ci.opencloud.eu/repos/3/pipeline/7/753) to see some caches purged.
- Part of: https://github.com/opencloud-eu/qa/issues/27#event-19199297494
- :robot:
=> [full-ci] purge browsers, opencloud web and playwright tracing cache

services/graph/pkg/service/v0/service.go, services/proxy/pkg/command/server.go, services/proxy/pkg/middleware/account_resolver.go, services/proxy/pkg/middleware/authentication.go, services/proxy/pkg/middleware/create_home.go, services/proxy/pkg/middleware/policies.go, services/proxy/pkg/middleware/selector_cookie.go, services/proxy/pkg/middleware/tracing.go
This PR has some smaller improvement for tracing
- use otelchi middleware in the graph service
- avoid unneeded extra span just for the request id attribute, by just adding it to the otelhttp created span
- create spans for the various proxy middlewares.
I am still somewhat unhappy with how the span for the middlewares are created. Each middleware's span is the child span for the middleware that is before it in the chain. I'd prefer if they were just childs of the top-level span created by the otel framework. I might be missing something obvious, but it seems really clumsy to create the spans that way because of the way how they are passed via context.
=> Tracing improvements

tests/acceptance/run.sh, vendor-bin/behat/composer.json
This PR reverts the behat version that was changed as temporary fix in this [PR](https://github.com/opencloud-eu/opencloud/pull/1501/files)
And also fixes the regex to [display the line number of failed tests](https://github.com/Behat/Behat/pull/1615)  -> A new feature introduced by Behat in `3.24.0`.
New format in `v3.24.0`:
```console
coreApiAuth/webDavMKCOLAuth.feature:42 (on line 50)
```
Previous versions v3.13:
```console
coreApiAuth/webDavMKCOLAuth.feature:42
```
So this PR adds another sed command that removes everything after `.feature:X`, including the new (on line X) text.
- Fixes https://github.com/opencloud-eu/opencloud/issues/1503
- :robot:
=> [full-ci][tests-only] revert behat version and fix regex on test script

services/search/README.md
little search readme [follow up pr](https://github.com/opencloud-eu/opencloud/pull/1513).
- it fixes one typo
- mentions the lack of scalability
=> fix(search): readme typos and mention the lack of scalability

CONTRIBUTING.md
the contributions document contains no information on branch naming which is fixed now... i found some typos and outdated anchors, fixed that too.
our requirements are not yet large enough to summarize them in a separate style guide... but every now and then we should look to see if it makes sense to bring them into a suitable dedicated format.
https://github.com/opencloud-eu/internal/issues/182
=> enhancement(docs): add branch naming styleguide and clean up the contribution guidelines

services/web/assets/themes/opencloud-dev/theme.json, services/web/assets/themes/opencloud/theme.json
The theming options `breakpoints`, `spacing`, `fontSizes` and `sizes` have been removed in Web.
see https://github.com/opencloud-eu/web/pull/1161
=> chore(web): remove unused theming options

services/postprocessing/pkg/metrics/metrics.go, services/postprocessing/pkg/service/service.go
It didn't really make sense in multi-node setups because items could be started and finished on different nodes.
/cc @micbar
=> Drop the "InProgress" metric

pkg/version/version.go
- run all tests on decomposed storage
- bump v3.5.0 version for upcoming rolling release
=> [decomposed] bump-version-v3.5.0

services/proxy/pkg/server/debug/server.go, tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md, tests/acceptance/expected-failures-localAPI-on-posix-storage.md
this fixes these errors
```json
{"level":"error","service":"proxy","error":"'nats reachability': could not connect to nats server: dial tcp: lookup opencloud-cluster on 10.43.0.10:53: no such host","time":"2025-09-22T13:36:22Z","line":"github.com/opencloud-eu/opencloud/pkg/handlers/checker.go:107","message":"check failed"}
```
=> use correct endpoint in nats check

tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
https://ci.opencloud.eu/repos/3/pipeline/291/168
```
Scenario Outline: send share invitation to group with different roles                            # /woodpecker/src/github.com/opencloud-eu/opencloud/tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature:100
Given user "Carol" has been created with default attributes                                    # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
And group "grp1" has been created                                                              # FeatureContext::groupHasBeenCreated()
And the following users have been added to the following groups                                # FeatureContext::theFollowingUserHaveBeenAddedToTheFollowingGroup()
| username | groupname |
| Brian    | grp1      |
| Carol …
```
=> apiTest-flaky: sync share before checking

services/collaboration/pkg/command/server.go, services/collaboration/pkg/helpers/discovery.go, services/collaboration/pkg/helpers/discovery_test.go, services/collaboration/pkg/helpers/registration.go, services/collaboration/pkg/server/grpc/option.go, services/collaboration/pkg/service/grpc/v0/option.go, services/collaboration/pkg/service/grpc/v0/service.go, services/collaboration/pkg/service/grpc/v0/service_test.go
We introduce AppURLs, a wrapper around atomic.Pointer that lets us use a ticker to periodically update the discovered WOPI actions without dying when it is not available on startup.
This allows us to get rid the hard requirement of the web office to be online and even allows us to pick up changes in its configuration automatically.
=> introduce AppURLs helper for atomic backgroud updates

opencloud/pkg/runtime/service/service.go
Fixes https://github.com/opencloud-eu/opencloud/issues/1528 
The root command already creates a signal notifier context, all we need to do in the runtine is add a cancel context.
=> let the runtime always create a cancel context

tests/acceptance/TestHelpers/GraphHelper.php, tests/acceptance/bootstrap/CliContext.php, tests/acceptance/bootstrap/FeatureContext.php, tests/acceptance/bootstrap/GraphContext.php, tests/acceptance/bootstrap/SpacesContext.php, tests/acceptance/features/apiActivities/activities.feature, tests/acceptance/features/apiGraph/userGDPRExport.feature, tests/acceptance/features/apiSpaces/changeSpaces.feature, tests/acceptance/features/apiSpaces/quota.feature, tests/acceptance/features/apiSpacesShares/shareOperations.feature, tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature, tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature, tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
- Removed `getUserIdByUserName()` → replaced with `getAttributeOfCreatedUser($user, 'id')`, which reduces the number of requests to `/graph/v1.0/users`.
- Added `getPersonalSpace()`, which retrieves a space by `userId` (instead of by name) via `/graph/v1.0/users/{userId}?%24select=&%24expand=drive`, ensuring the correct personal space is found even in case of duplicates (e.g., soft-deleted users).
=> [full-ci] getting personal space by userId instead of userName

services/idp/src/containers/Login/Login.jsx
Fix is needed for https://github.com/opencloud-eu/web/issues/889
The input fields were not valid autocomplete values according to the HTML specificationkopano-account.
=> fix: use valid autocomplete values (axe autocomplete-valid)
